-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Drinkit CASCADE;
DROP TABLE IF EXISTS Ainesosat CASCADE;
DROP TABLE IF EXISTS Drinkki_Aineet CASCADE;